--- #YAML:1.0
name: DBIx-Class-DateTime-Epoch
version: 0.02
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: Automatic inflation/deflation of epoch-based DateTime objects for DBIx::Class
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
