---
name: DBIx-Class-DateTime-Epoch
version: 0.01
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: Automatic inflation/deflation of epoch-based DateTime objects for DBIx::Class
license: perl
requires:
  DBIx::Class: 0
  DateTime: 0
build_requires:
  Test::More: 0
provides:
  DBIx::Class::DateTime::Epoch:
    file: lib/DBIx/Class/DateTime/Epoch.pm
    version: 0.01
generated_by: Module::Build version 0.2611
